export type GenAiAtomicTopic = { id: string; title: string; focus: string };

export type GenAiTopic = {
  id: string;
  title: string;
  track: string;
  why: string;
  subtopics: GenAiAtomicTopic[];
};

const focusByTopic: Record<string, string[]> = {
  'ml-foundations': ['Turn a product problem into inputs and a target.', 'Explain which data is used to learn and which data is used to judge.', 'Connect model mistakes to the quantity being optimized.', 'Explain how parameters move toward a lower error.', 'Diagnose whether the model is too simple or too specialized.', 'Choose the right metric when errors have different costs.'],
  'deep-learning': ['Trace one input through layers to a prediction.', 'Explain logits before probabilities and decisions.', 'Show how an error signal reaches earlier layers.', 'Compare smooth, bounded, and sparse nonlinearities.', 'Explain why normalization stabilizes training.', 'Separate regularization from optimization behavior.'],
  transformers: ['Explain what information each token can look at.', 'Calculate the weighted combination of value vectors.', 'Explain why multiple attention heads help.', 'Prevent a language model from seeing future tokens.', 'Explain why deep networks can still train.', 'Choose an architecture for classification, generation, or translation.'],
  tokenization: ['Explain why the same sentence can become different token counts.', 'Describe how frequent pieces become reusable tokens.', 'Know the tokens added by the model protocol.', 'Estimate context cost before sending a request.', 'Explain what gets truncated when context is too long.', 'Explain how order is represented without recurrence.'],
  embeddings: ['Explain why similar meaning should produce nearby vectors.', 'Compare semantic vectors with exact keyword matching.', 'Use cosine similarity without confusing it with probability.', 'Choose distance based on the retrieval objective.', 'Match an embedding model to language and domain.', 'Keep search results stable across model upgrades.'],
  'llm-training': ['Explain what the model predicts at each position.', 'Describe why the target is the next token.', 'Spot leakage, duplication, and low-quality training data.', 'Separate learning language from following instructions.', 'Explain what preference data teaches beyond correctness.', 'Compare reward-based and direct preference optimization.'],
  prompting: ['Keep instructions, data, and constraints unambiguous.', 'Know when examples improve behavior and when they add noise.', 'Separate system rules from user-provided content.', 'Break a hard request into smaller verifiable steps.', 'Constrain output so downstream code can parse it.', 'Detect prompt regressions as templates evolve.'],
  rag: ['Trace a document from upload to retrievable chunk.', 'Choose chunk boundaries that preserve meaning.', 'Filter retrieval by tenant, time, or document type.', 'Explain where retrieval sits relative to generation.', 'Fit only the most useful evidence into context.', 'Link claims back to the source evidence.'],
  'vector-search': ['Create comparable vectors for a query and a document.', 'Trade search speed against recall at scale.', 'Choose an index based on data size and update pattern.', 'Combine exact terms with semantic similarity.', 'Use a second model to reorder candidate results.', 'Set top-k and threshold from evaluation data.'],
  'fine-tuning': ['Prove that prompting or RAG is insufficient first.', 'Teach a consistent behavior from representative examples.', 'Adapt a model without updating every parameter.', 'Reduce memory cost while preserving adaptation quality.', 'Prevent narrow or noisy examples from shaping behavior.', 'Recognize forgetting and training-data leakage.'],
  evaluation: ['Build examples that represent real user traffic.', 'Choose a metric that matches the task and failure cost.', 'Compare output to a reference without missing useful variation.', 'Identify bias and instability in model-based judging.', 'Score responses with a repeatable human rubric.', 'Connect offline scores to live product outcomes.'],
  agents: ['Define a tool contract the model can use safely.', 'Explain the request and result schema for a function call.', 'Separate deciding the next action from executing it.', 'Validate tool output before feeding it back to the model.', 'Recover from transient failures without duplicating actions.', 'Stop loops and require approval for risky actions.'],
  memory: ['Persist only the state needed for the current turn.', 'Manage context that cannot fit in one request.', 'Compress old turns without losing important facts.', 'Retrieve durable memories only when relevant.', 'Represent preferences without storing unnecessary personal data.', 'Make deletion real across indexes, caches, and logs.'],
  safety: ['Block instructions that try to override system intent.', 'Treat retrieved documents as untrusted input.', 'Keep secrets and personal data out of prompts and logs.', 'Give each tool the smallest required permission.', 'Catch unsafe content without hiding useful answers.', 'Limit abuse while preserving legitimate usage.'],
  inference: ['Separate prompt processing from token generation.', 'Return partial output without losing request control.', 'Improve throughput by serving requests together.', 'Schedule uneven generation workloads efficiently.', 'Reuse attention state across generated tokens.', 'Trade model size and precision against quality and memory.'],
  scaling: ['Route requests by model, region, tenant, or capability.', 'Protect the service from traffic spikes and noisy users.', 'Move slow work out of the synchronous request path.', 'Reuse safe responses without serving stale or private data.', 'Degrade gracefully when the primary model is unavailable.', 'Prevent queues from growing faster than workers can drain them.'],
  multimodal: ['Represent visual and textual signals in one request.', 'Understand how images become model-readable tokens.', 'Extract text while preserving document structure.', 'Use layout and relationships, not only plain OCR text.', 'Separate transcription errors from reasoning errors.', 'Retrieve evidence across text, images, and other modalities.'],
  mlops: ['Follow one request across model and retrieval components.', 'Log enough context to debug without leaking user data.', 'Measure tokens, latency, errors, and cost together.', 'Detect when incoming data no longer matches training data.', 'Detect quality decay after model or prompt changes.', 'Turn user feedback into prioritized model improvements.'],
  'ai-system-design': ['Clarify users, constraints, and what success means.', 'Turn product expectations into measurable service targets.', 'Choose the model, context, and control strategy together.', 'Show the data path from source to final answer.', 'Estimate throughput, storage, tokens, and failure capacity.', 'Explain what breaks first and how the design recovers.'],
  'ai-product-thinking': ['Connect the feature to a real user job.', 'Balance usefulness against harmful or expensive mistakes.', 'Define quality and guardrails before choosing a model.', 'Compare cost drivers across model and architecture choices.', 'Decide where automation must hand off to a person.', 'Roll out safely and learn from measured user behavior.'],
};

function atoms(topicId: string, titles: string[]): GenAiAtomicTopic[] {
  return titles.map((title, index) => ({ id: `${topicId}-${index + 1}`, title, focus: focusByTopic[topicId][index] }));
}

export const genAiTopics: GenAiTopic[] = [
  { id: 'ml-foundations', title: 'ML foundations for GenAI', track: 'Start here', why: 'Build the minimum ML intuition needed to explain how models learn and fail.', subtopics: atoms('ml-foundations', ['Features, labels, and examples', 'Training, validation, and test split', 'Loss functions and empirical risk', 'Gradient descent and learning rate', 'Underfitting, overfitting, and regularization', 'Precision, recall, and calibration']) },
  { id: 'deep-learning', title: 'Deep learning essentials', track: 'Start here', why: 'Learn the neural network mechanics that sit underneath modern AI systems.', subtopics: atoms('deep-learning', ['Perceptron and multilayer network', 'Forward pass and logits', 'Backpropagation and chain rule', 'Activation functions', 'Batch normalization and layer normalization', 'Dropout and weight decay']) },
  { id: 'transformers', title: 'Transformers and attention', track: 'Core models', why: 'Understand the architecture behind most modern language models.', subtopics: atoms('transformers', ['Query, key, and value', 'Scaled dot-product attention', 'Multi-head attention', 'Causal masking', 'Residual connections', 'Encoder-only, decoder-only, and encoder-decoder']) },
  { id: 'tokenization', title: 'Tokenization and context', track: 'Core models', why: 'Know exactly what an LLM receives and why context limits matter.', subtopics: atoms('tokenization', ['Characters, words, and subwords', 'BPE tokenization', 'Special tokens', 'Token count and cost', 'Context window', 'Positional encoding and position limits']) },
  { id: 'embeddings', title: 'Embeddings and similarity', track: 'Core models', why: 'Explain how language becomes a representation that systems can compare and retrieve.', subtopics: atoms('embeddings', ['What an embedding represents', 'Dense versus sparse vectors', 'Cosine similarity', 'Distance metrics', 'Embedding model choice', 'Embedding drift and versioning']) },
  { id: 'llm-training', title: 'LLM pretraining and post-training', track: 'Core models', why: 'Describe the stages that turn raw data into a useful assistant.', subtopics: atoms('llm-training', ['Next-token prediction', 'Causal language modeling', 'Dataset construction and deduplication', 'Pretraining versus instruction tuning', 'Preference data and reward models', 'RLHF, DPO, and alignment']) },
  { id: 'prompting', title: 'Prompt engineering', track: 'Application patterns', why: 'Turn vague requests into reliable and testable model behavior.', subtopics: atoms('prompting', ['Instruction hierarchy', 'Zero-shot and few-shot prompting', 'Role and context separation', 'Prompt decomposition', 'Structured JSON output', 'Prompt versioning and regression tests']) },
  { id: 'rag', title: 'Retrieval-augmented generation', track: 'Application patterns', why: 'Learn the most common pattern for grounding an LLM in private or changing data.', subtopics: atoms('rag', ['Document ingestion', 'Chunk size and overlap', 'Metadata filtering', 'Retrieve-then-read flow', 'Context assembly', 'Grounding and citations']) },
  { id: 'vector-search', title: 'Vector search and retrieval', track: 'Application patterns', why: 'Design the search layer that supplies relevant context to a model.', subtopics: atoms('vector-search', ['Embedding query and documents', 'Approximate nearest neighbor search', 'Index types and recall', 'Keyword plus vector hybrid search', 'Reranking', 'Top-k and relevance thresholds']) },
  { id: 'fine-tuning', title: 'Fine-tuning and PEFT', track: 'Model adaptation', why: 'Choose correctly between prompting, retrieval, and training.', subtopics: atoms('fine-tuning', ['When fine-tuning is justified', 'Supervised fine-tuning', 'LoRA and adapters', 'Quantized fine-tuning', 'Training data quality', 'Catastrophic forgetting and leakage']) },
  { id: 'evaluation', title: 'LLM evaluation', track: 'Reliability', why: 'Measure quality systematically instead of trusting an impressive demo.', subtopics: atoms('evaluation', ['Evaluation dataset design', 'Task-specific metrics', 'Reference-based evaluation', 'LLM-as-judge bias', 'Human evaluation rubric', 'Offline versus online evaluation']) },
  { id: 'agents', title: 'Agents and tool use', track: 'Reliability', why: 'Understand the loop between reasoning, actions, observations, and answers.', subtopics: atoms('agents', ['Tool schema design', 'Function calling', 'Planner and executor', 'Tool result validation', 'Retries and timeouts', 'Stopping rules and human approval']) },
  { id: 'memory', title: 'Memory and conversation state', track: 'Reliability', why: 'Design what an assistant should remember, retrieve, summarize, or forget.', subtopics: atoms('memory', ['Conversation state', 'Short-term context window', 'Rolling summaries', 'Long-term memory retrieval', 'User preference storage', 'Deletion and privacy controls']) },
  { id: 'safety', title: 'Safety and security', track: 'Production thinking', why: 'Build systems that handle misuse, prompt injection, and sensitive data.', subtopics: atoms('safety', ['Direct prompt injection', 'Indirect prompt injection', 'Sensitive data handling', 'Tool permission boundaries', 'Output filtering', 'Abuse monitoring and rate limits']) },
  { id: 'inference', title: 'Inference and serving', track: 'Production thinking', why: 'Know what controls latency, throughput, and cost for each request.', subtopics: atoms('inference', ['Prefill and decode', 'Streaming tokens', 'Batching', 'Continuous batching', 'KV cache', 'Quantization']) },
  { id: 'scaling', title: 'Scaling GenAI systems', track: 'Production thinking', why: 'Connect model behavior to queues, caches, limits, and graceful degradation.', subtopics: atoms('scaling', ['Request routing', 'Rate limiting', 'Async job queues', 'Response caching', 'Fallback models', 'Concurrency and backpressure']) },
  { id: 'multimodal', title: 'Multimodal models', track: 'Frontier patterns', why: 'Cover the interview basics for images, audio, video, and documents.', subtopics: atoms('multimodal', ['Vision-language input', 'Image tokenization', 'OCR pipeline', 'Document layout understanding', 'Audio transcription', 'Cross-modal retrieval']) },
  { id: 'mlops', title: 'MLOps and observability', track: 'Production thinking', why: 'Monitor quality, cost, drift, and failures after launch.', subtopics: atoms('mlops', ['Request tracing', 'Prompt and response logging', 'Latency and token metrics', 'Data drift', 'Model drift', 'Feedback and incident loop']) },
  { id: 'ai-system-design', title: 'GenAI system design', track: 'Interview synthesis', why: 'Combine models, data, retrieval, safety, and operations into one design.', subtopics: atoms('ai-system-design', ['Clarify product requirements', 'Define quality and latency SLOs', 'Choose model and context strategy', 'Design data and retrieval flow', 'Estimate traffic and capacity', 'Explain failure modes and tradeoffs']) },
  { id: 'ai-product-thinking', title: 'AI product and cost thinking', track: 'Interview synthesis', why: 'Show that you can choose the right AI feature, metric, and budget.', subtopics: atoms('ai-product-thinking', ['User job and failure cost', 'Success metric and guardrail metric', 'Quality versus latency tradeoff', 'Token and model cost', 'Human review threshold', 'Rollout and experimentation']) },
];

export const allGenAiAtomicTopics = genAiTopics.flatMap(topic => topic.subtopics);

export type GenAiPair = {
  id: string;
  topic: GenAiTopic;
  subtopics: GenAiAtomicTopic[];
};

export const genAiPairs: GenAiPair[] = [];
for (const topic of genAiTopics) {
  for (let index = 0; index < topic.subtopics.length; index += 2) {
    genAiPairs.push({ id: `${topic.id}-${index / 2 + 1}`, topic, subtopics: topic.subtopics.slice(index, index + 2) });
  }
}
